### ISSUE TITLE
Multiple PHP versions?

### ISSUE THREAD

**Issue by wintercounter** [sensational/sassphp#18]
I was able to install the extension for the system PHP easily which is 5.5. I also have 5.4 and 5.3 on my server and I should make it for those also. Any advice? I tried to create a custin phpize init file and changed the paths in the configured Makefile but no success. Can someone point me to the right direction?

**Comment by pilif** [comment]
This question if beyond the scope of this project as this same question applies to any PHP extension.

Still: I can help you:

Unfortunately, just having different versions of `phpize` is not enough to create a `configure` script that will actually create a correct make file because `phpize` calls into other things related to the PHP install based on `$PATH`.

The only way to make this work correctly is if you have separated the various PHP installs into their own prefixes and then you adjust `$PATH` to only contain the correct PHP version's `bin` directory before calling `phpize`.

This will build a correct extension for the respective PHP version.

**Comment by wintercounter** [comment]
This sounds a little bit risky to play with ona  production server :) Maybe i'll setup a free vps with the corresponding PHP version, compile the extension and copy the .so file from there. Anyway, i really appreciate the help, thanks ;)

**Comment by pilif** [comment]
Well. On a production server, you shouldn't have any compiler running to begin with :P

I was talking about your packaging server of course.
